In [1]:
import os
import json
import pandas as pd

In [4]:
directory = 'results_related'

df_twitter_final = pd.DataFrame()

frames = list()

# Loop over files in the directory
for filename in os.scandir(directory):
    with open(f'./{directory}/{filename.name}', encoding='utf8') as json_file:
        data = json.load(json_file)

    df_twitter = pd.DataFrame(data)

    # Convert date to datetime format
    df_twitter['created_at'] = pd.to_datetime(df_twitter['created_at'], format='%Y-%m-%d %H:%M:%S')

    # Set date column as index
    df_twitter.set_index('created_at', inplace=True)

    # Order by date
    df_twitter.sort_index(inplace=True)

    frames.append(df_twitter)

    print (filename, df_twitter.loc['2018':'2022-07-13'].shape)

# for df in frames:
#     df_twitter_final = df_twitter_final.append(df)

<DirEntry 'acionistacombr.json'> (2804, 7)
<DirEntry 'arkoadvice.json'> (586, 7)
<DirEntry 'BloombergBrasil.json'> (1291, 7)
<DirEntry 'BrazilJournal.json'> (3163, 7)
<DirEntry 'bussoladoinves.json'> (2980, 7)
<DirEntry 'EstadaoEconomia.json'> (3192, 7)
<DirEntry 'Fatosdomercado.json'> (1311, 7)
<DirEntry 'folha_mercado.json'> (2697, 7)
<DirEntry 'infomoney.json'> (2525, 7)
<DirEntry 'InvestidoresO.json'> (1464, 7)
<DirEntry 'InvestingBrasil.json'> (2181, 7)
<DirEntry 'valoreconomico.json'> (2218, 7)
<DirEntry 'valorinveste.json'> (2318, 7)

In [12]:
df_twitter_final.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 19985 entries, 2021-09-09 16:22:27 to 2022-05-03 14:15:19
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tweet_id        19985 non-null  object
 1   search_dt       19985 non-null  object
 2   text            19985 non-null  object
 3   user_id         19985 non-null  object
 4   screen_name     19985 non-null  object
 5   rt_count        19985 non-null  int64
 6   favorite_count  19985 non-null  int64
dtypes: int64(2), object(5)
memory usage: 1.2+ MB

In [13]:
df_twitter_final.sample(10)

,tweet_id,search_dt,text,user_id,screen_name,rt_count,favorite_count
created_at,,,,,,,
2021-12-03 21:27:49,1466927184724086790,2022-05-03 14:13:42,Eletrobras (ELET3): processo de privatização e...,778276232081342464,sunonoticias,0,6
2022-04-06 10:00:23,1511690280650612740,2022-05-03 14:37:18,Petrobras (PETR4): confira quais nomes entrara...,59773459,infomoney,0,11
2022-03-09 09:33:20,1501536613435944960,2022-05-03 14:16:08,Abertura de mercado: o que esperar para bolsa ...,49292227,InvestingBrasil,0,5
2021-12-22 22:54:51,1473834457681567746,2022-05-03 14:18:01,MOVIDA - Outros avisos/Dividendos/Juros sobre ...,1124834863520022529,Fatosdomercado,0,7
2022-03-22 11:53:04,1506282818854342659,2022-05-03 14:13:32,Embraer (EMBR3): Eve conclui estudo para ‘carr...,778276232081342464,sunonoticias,0,0
2022-04-19 13:52:36,1516459764007546885,2022-05-03 14:16:32,Empresa alemã de software SAP planeja sair tot...,51150679,leiamoneytimes,0,2
2022-02-25 15:16:57,1497274431453945866,2022-05-03 14:37:24,"Com distribuições recordes, Vale e Petrobras p...",59773459,infomoney,0,15
2022-02-24 18:46:57,1496964892410142721,2022-05-03 14:16:58,Bolsas de NY revertem perdas fortes repercutin...,1113533606247436289,valorinveste,1,4
2022-03-11 22:18:52,1502454042819284992,2022-05-03 14:17:34,"Quer ouvir, em 1 minuto, todas as novidades de...",74550038,B3_Oficial,1,12
2022-05-03 11:02:35,1521490407431057410,2022-05-03 14:16:26,TSE cancela convite para UE observar eleições ...,51150679,leiamoneytimes,2,2

In [14]:
assert len(df_twitter_final.tweet_id.unique()) == df_twitter_final.shape[0]

In [15]:
# Save df object
df_twitter_final.to_pickle('./twitter_df.pkl')